# Base configs
baseurl: "https://browncony.world"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: ""

# UI configs
title: "World of Brown and Cony"
subtitle: "Brown Cony all around the world"
author: "BrownCony"
bio: "BrownCony bio"
publicise: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
#social_urls:
#  facebook: "https://www.facebook.com/ramswaroop"
#  twitter: "https://www.twitter.com/ramswarooppatra"
#  instagram: "https://www.instagram.com/ramswarooppatra"
#  dribbble: "https://dribbble.com/ramswaroop"
#  linkedin: "https://in.linkedin.com/in/ramswarooppatra"
#  github: "https://www.github.com/ramswaroop"
  
